core/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Email


class ContactForm(FlaskForm):
    name = StringField("Ім'я", validators=[DataRequired()])
    email = StringField("E-mail", validators=[DataRequired(), Email()])
    title = StringField("Тема", validators=[DataRequired()])
    content = TextAreaField("Повідомлення", validators=[DataRequired()])
    submit = SubmitField("Відправити")

core/__init__.py
from flask import Flask
from config import Config


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    from core.main.routes import main

    from core.errors.handlers import errors

    app.register_blueprint(main)
    app.register_blueprint(errors)

    return app

core/main/routes.py
from flask import render_template, redirect, url_for, Blueprint

from core.main.forms import ContactForm

from apps import APPS

main = Blueprint("main", __name__)


@main.route("/")
@main.route("/home")
def home():
    return render_template("main/home.html", apps=APPS)


@main.route("/about")
def about():
    return render_template("main/about.html", title="Про сервіс")


@main.route("/contact", methods=["GET", "POST"])
def contact():
    form = ContactForm()
    if form.validate_on_submit():
        return redirect(url_for("main.home"))
    return render_template("main/contact.html", title="Контакти", form=form)

core/templates/_footer.html
<!-- Footer -->
<footer class="footer">
  <!-- Footer Links -->
  <div class="container text-center text-md-left">
    <!-- Grid row -->
    <div class="row">
      <!-- Grid column -->
      <div class="footer-links col-md-3">
        <!-- Links -->
        <h5>Сталеві конструкції</h5>
        <ul>
          <li>
            <a href="#">Сервіс 1</a>
          </li>
          <li>
            <a href="#">Сервіс 2</a>
          </li>
          <li>
            <a href="#">Сервіс 3</a>
          </li>
          <li>
            <a href="#">Сервіс 4</a>
          </li>
        </ul>
      </div>
      <!-- Grid column -->
      <!-- Grid column -->
      <div class="footer-links col-md-3">
        <!-- Links -->
        <h5>Бетонні конструкції</h5>
        <ul>
          <li>
            <a href="#">Сервіс 1</a>
          </li>
          <li>
            <a href="#">Сервіс 2</a>
          </li>
          >
        </ul>
      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="footer-links col-md-3">
        <!-- Links -->
        <h5>Інше</h5>
        <ul>
          <li>
            <a href="#">Сервіс 1</a>
          </li>
          <li>
            <a href="#">Сервіс 2</a>
          </li>
        </ul>
      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="footer-links col-md-3">
        <!-- Links -->
        <h5>Посилання</h5>

        <ul>
          <li>
            <a href="{{ url_for('main.home') }}">Головна</a>
          </li>
          <li>
            <a href="{{ url_for('main.about') }}">Про сервіс</a>
          </li>
          <li>
            <a href="{{ url_for('main.contact') }}">Контакти</a>
          </li>
        </ul>
      </div>
      <!-- Grid column -->
    </div>
    <!-- Grid row -->
  </div>
  <!-- Footer Links -->
  <div id="sub-footer">
    <div class="container">
      <div class="row">
        <div class="col-6">
          <div class="copyright">
            <p>
              <span>&copy; Sapsan-build 2020 All right reserved.</span>
            </p>
          </div>
        </div>
        <div class="col-6">
          <ul class="social-network">
            <li>
              <a href="#" data-placement="top" title="Facebook"
                ><i class="fa fa-facebook"></i
              ></a>
            </li>
            <li>
              <a href="#" data-placement="top" title="Twitter"
                ><i class="fa fa-twitter"></i
              ></a>
            </li>
            <li>
              <a href="#" data-placement="top" title="Linkedin"
                ><i class="fa fa-linkedin"></i
              ></a>
            </li>
            <li>
              <a href="#" data-placement="top" title="Pinterest"
                ><i class="fa fa-pinterest"></i
              ></a>
            </li>
            <li>
              <a href="#" data-placement="top" title="Google plus"
                ><i class="fa fa-google-plus"></i
              ></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>
<!-- Footer -->

core/templates/_navbar.html
<nav class="navbar navbar-expand-md navbar-light">
  <div class="container">
    <div class="navbar-brand mr-4">
      <a href="{{url_for('main.home')}}">
        <img
          src="{{ url_for('static', filename='img/logo.png') }}"
          alt="logo"
        />
      </a>
    </div>
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarToggle"
      aria-controls="navbarToggle"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarToggle">
      <!-- Navbar Right Side -->
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link active" href="{{url_for('main.home')}}">Головна</a>
        </li>
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarServisesDropdown"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
          >
            Сервіси
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarServisesDropdown">
            <a class="dropdown-item" href="#">Сервіс 1</a>
            <a class="dropdown-item" href="#">Сервіс 2</a>
            <a class="dropdown-item" href="#">Сервіс 3</a>
            <a class="dropdown-item" href="#">Сервіс 4</a>
            <a class="dropdown-item" href="#">Сервіс 5</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main.about') }}">Про сервіс</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main.contact') }}">Контакти</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

core/templates/layout.html
<!DOCTYPE html>
<html lang="uk">
  <head>
    <meta charset="utf-8" />

    {% if title %}
    <title>{{ title }} - SAPSAN</title>
    {% else %}
    <title>SAPSAN-BUILD</title>
    {% endif %}

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="" />

    <!-- bootstrap css -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />

    <!-- custom css -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='css/style.css') }}"
    />

    <!-- font awesome -->
    <script
      src="https://kit.fontawesome.com/5de3e67cfc.js"
      crossorigin="anonymous"
    ></script>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <div id="wrapper">
      <header>
        {% include '_navbar.html' %}
      </header>
      <main>
        {% block content %}{% endblock %}
      </main>
      <footer>
        {% include '_footer.html' %}
      </footer>
    </div>
    <!-- javascript js -->
    <script
      src="https://code.jquery.com/jquery-3.5.1.min.js"
      integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"
      integrity="sha384-1CmrxMRARb6aLqgBO7yyAxTOQE2AKb9GfXnEo760AUcUmFx3ibVJJAzGytlQcNXd"
      crossorigin="anonymous"
    ></script>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <script
      id="MathJax-script"
      async
      src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
    ></script>
  </body>
</html>

core/templates/main/about.html
{% extends "layout.html" %} {% block content %}

<section id="inner-headline">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h2 class="page-title">Про сервіс</h2>
      </div>
    </div>
  </div>
</section>

<section id="content">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="about">
          <h5>
            Головною ідеєю сервісу є створення програм, що допоможуть
            інженерам-проектувальникам, архітекторам та іншим будівельникам у їх
            професійній діяльносі.
          </h5>
          <p>Наразі сервіси поділено відповідно до типу несучих конструкці</p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          <div class="serv-type">
            <h5>
              Сталеві конструкці
            </h5>
            <img
              src="{{ url_for('static', filename='img/types/steel.jpg') }}"
              alt="steel"
              class="img-fluid"
            />
          </div>
        </div>
        <div class="col-md-4">
          <div class="serv-type">
            <h5>
              Бетонні конструкці
            </h5>
            <img
              src="{{ url_for('static', filename='img/types/concreate.jpg') }}"
              alt="concreate"
              class="img-fluid"
            />
          </div>
        </div>
        <div class="col-md-4">
          <div class="serv-type">
            <h5>
              Інше
            </h5>
            <img
              src="{{ url_for('static', filename='img/types/other.jpg') }}"
              alt="other"
              class="img-fluid"
            />
          </div>
        </div>
      </div>
    </div>

    <div class="service-description">
      <div class="row">
        <div class="col-3">
          <img
            src="{{ url_for('static', filename='img/solidgrey.png') }}"
            alt="servise1"
            class="img-fluid"
          />
        </div>
        <div class="col-9">
          <div class="serv-info">
            <h5>Сервіс №1</h5>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse
              necessitatibus labore architecto cupiditate reiciendis deserunt
              laudantium veniam quis deleniti asperiores id doloremque
              perspiciatis unde velit, nobis voluptatum fugiat consequuntur
              iusto.
            </p>
          </div>
        </div>
      </div>
    </div>

    <div class="service-description">
      <div class="row">
        <div class="col-3">
          <img
            src="{{ url_for('static', filename='img/solidgrey.png') }}"
            alt="servise1"
            class="img-fluid"
          />
        </div>
        <div class="col-9">
          <div class="serv-info">
            <h5>Сервіс №1</h5>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse
              necessitatibus labore architecto cupiditate reiciendis deserunt
              laudantium veniam quis deleniti asperiores id doloremque
              perspiciatis unde velit, nobis voluptatum fugiat consequuntur
              iusto.
            </p>
          </div>
        </div>
      </div>
    </div>

    <div class="service-description">
      <div class="row">
        <div class="col-3">
          <img
            src="{{ url_for('static', filename='img/solidgrey.png') }}"
            alt="servise1"
            class="img-fluid"
          />
        </div>
        <div class="col-9">
          <div class="serv-info">
            <h5>Сервіс №1</h5>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse
              necessitatibus labore architecto cupiditate reiciendis deserunt
              laudantium veniam quis deleniti asperiores id doloremque
              perspiciatis unde velit, nobis voluptatum fugiat consequuntur
              iusto.
            </p>
          </div>
        </div>
      </div>
    </div>

    <!-- Heading -->
    <div class="row">
      <div class="col-12">
        <div class="block-heading">
          <h4>Наша команда</h4>
        </div>
      </div>
    </div>

    <!-- Our team starts -->

    <div class="row">
      <div class="col-md-3 col-sm-6">
        <div class="team-member">
          <img
            src="{{ url_for('static', filename='img/team/CEO.jpg') }}"
            alt="ceo"
          />
          <!-- Name -->
          <h5>Вдовкін Олександр</h5>
          <span>Керівник проекту</span>
        </div>
      </div>

      <div class="col-md-3 col-sm-6">
        <div class="team-member">
          <img
            src="{{ url_for('static', filename='img/team/structural_engineer.jpg') }}"
            alt="structural_engineer"
          />

          <h5>Вдовкін Олександр</h5>
          <span>Інженер-проектувальник</span>
        </div>
      </div>

      <div class="col-md-3 col-sm-6">
        <div class="team-member">
          <img
            src="{{ url_for('static', filename='img/team/developer.jpg') }}"
            alt="developer"
          />
          <!-- Name -->
          <h5>Вдовкін Олександр</h5>
          <span>Програміст</span>
        </div>
      </div>

      <div class="col-md-3 col-sm-6">
        <div class="team-member">
          <img
            src="{{ url_for('static', filename='img/team/designer.jpg') }}"
            alt="designer"
          />
          <h5>Вдовкін Олександр</h5>
          <span>Дизайнер</span>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

core/templates/main/contact.html
{% extends "layout.html" %} {% block content %}

<section id="inner-headline">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h2 class="page-title">Контакти</h2>
      </div>
    </div>
  </div>
</section>

<section id="contacts">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h4>Контакти</h4>
        <div class="contacts-field">
          <i class="far fa-envelope fa-lg"></i>
          <a href="mailto:sapsanbuild@gmail.com">sapsanbuild@gmail.com</a>
        </div>
        <ul class="social-network">
          <li>
            <a href="#" data-placement="top" title="Facebook"
              ><i class="fa fa-facebook fa-3x"></i
            ></a>
          </li>
          <li>
            <a href="#" data-placement="top" title="Twitter"
              ><i class="fa fa-twitter fa-3x"></i
            ></a>
          </li>
          <li>
            <a href="#" data-placement="top" title="Linkedin"
              ><i class="fa fa-linkedin fa-3x"></i
            ></a>
          </li>
          <li>
            <a href="#" data-placement="top" title="Pinterest"
              ><i class="fa fa-pinterest fa-3x"></i
            ></a>
          </li>
          <li>
            <a href="#" data-placement="top" title="Google plus"
              ><i class="fa fa-google-plus fa-3x"></i
            ></a>
          </li>
        </ul>

        <div class="social-contacts"></div>
      </div>
      <div class="col-md-6">
        <div class="contact-form">
          <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
              <legend class="border-bottom mb-4">Зворотній зв'язок</legend>
              <div class="form-group">
                {{ form.name.label(class="form-control-label") }} {% if
                form.name.errors %} {{ form.name(class="form-control
                form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                  {% for error in form.name.errors %}
                  <span>{{ error }}</span>
                  {% endfor %}
                </div>
                {% else %} {{ form.name(class="form-control form-control-lg") }}
                {% endif %}
              </div>
              <div class="form-group">
                {{ form.email.label(class="form-control-label") }} {% if
                form.email.errors %} {{ form.email(class="form-control
                form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                  {% for error in form.email.errors %}
                  <span>{{ error }}</span>
                  {% endfor %}
                </div>
                {% else %} {{ form.email(class="form-control form-control-lg")
                }} {% endif %}
              </div>
              <div class="form-group">
                {{ form.title.label(class="form-control-label") }} {% if
                form.title.errors %} {{ form.title(class="form-control
                form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                  {% for error in form.title.errors %}
                  <span>{{ error }}</span>
                  {% endfor %}
                </div>
                {% else %} {{ form.title(class="form-control form-control-lg")
                }} {% endif %}
              </div>
              <div class="form-group">
                {{ form.content.label(class="form-control-label") }} {% if
                form.content.errors %} {{ form.content(class="form-control
                form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                  {% for error in form.content.errors %}
                  <span>{{ error }}</span>
                  {% endfor %}
                </div>
                {% else %} {{ form.content(class="form-control form-control-lg")
                }} {% endif %}
              </div>
            </fieldset>
            <div class="form-group">
              {{ form.submit(class="btn btn-standart") }}
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

core/templates/main/home.html
{% extends "layout.html" %} {% block content %}

<section id="inner-headline">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h2 class="page-title">Головна</h2>
      </div>
    </div>
  </div>
</section>
<section id="content">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center my-auto">
        <div class="main-desctiption">
          <p>
            На данній сторінці розміщено перелік прикладних програм для
            автомаизації розразункків.
            <a href="{{ url_for('main.about') }}">Детальніше про сервіс</a>
          </p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <ul class="apps-filter text-center">
          <li class="all active"><a href="#">Всі</a></li>
          <li class="web"><a href="#" title="">Сталеві конструкції</a></li>
          <li class="icon"><a href="#" title="">Бетонні конструкції</a></li>
          <li class="graphic"><a href="#" title="">Інше</a></li>
        </ul>
        <!-- <div class="clearfix"></div> -->

        <div class="row">
          {% for app in apps %}
          <div class="col-lg-3 col-sm-6 p-2">
            <div class="apps-pic" data-id="id-0" data-type="web">
              <img
                src="{{ url_for('static', filename=app.img) }}"
                alt="{{app.link}} preview picture"
              />

              <a href="#" class="hover-wrap"
                ><span class="apps-links">{{app.name}}</span></a
              >
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}